### ISSUE TITLE
コハルのデバフが上書きされる

### ISSUE THREAD

**Issue by dn228** [aki-m/aigistools#10]
コハルのスキルによるデバフが、単体なら正常に計算されますが
他のスキルと併用すると上書きされデバフ効果が適用されなくなるようです。
修正お願いします。

**Comment by aki-m** [comment]
調べてみます

**Comment by aki-m** [comment]
検証(ケース１６) → https://aki-m.github.io/aigistools/round/round.html
デバフの重複確認が残

**Comment by aki-m** [comment]
堕姫、春着ロゼット、デューオで確認。
どれも別枠で、打ち消しなしのもよう
