### ISSUE TITLE
シャディアのバフが実際の効果と異なります

### ISSUE THREAD

**Issue by kmkmtrtr** [aki-m/aigistools#7]
シャディアの覚醒アビは実際はHP+10%ですが、バフ試算表では魔耐+10%で計算されてしまいます。
![image](https://user-images.githubusercontent.com/25153546/51788442-7f521000-21c1-11e9-8bd9-bd411761b130.png)
![image](https://user-images.githubusercontent.com/25153546/51788451-955fd080-21c1-11e9-85ab-dcf7de8ba5d7.png)

**Comment by aki-m** [comment]
ありがとうございます。修正しました。
